name: CI/CD Pipeline

# Run the workflow whenever code is pushed to the 'main' branch or a pull request is opened
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker to build the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/portfolio:latest

  # Deployment job: deploy the Docker image to your server
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Deploy the built image to the server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
            host: ${{ secrets.CLOUD_SERVER_IP }}
            username: ${{ secrets.CLOUD_SERVER_USER }}
            password: ${{ secrets.CLOUD_SERVER_PASSWORD }}
            script: |
                docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio:latest
                docker stop portfolio || true
                docker rm portfolio || true
                docker run -d -p 80:80 -p 3306:3306 --name portfolio ${{ secrets.DOCKER_USERNAME }}/portfolio:latest
